package:
  name: regex
  version: 2015.11.22

source:
  fn: regex-2015.11.22.tar.gz
  url: https://pypi.python.org/packages/source/r/regex/regex-2015.11.22.tar.gz
  md5: 0bd2c23059f99cbaf9046000d51d3de7

build:
  number: 0

requirements:
  build:
    - python
    - setuptools
  run:
    - python

test:
    imports:
        - regex

about:
  home: https://bitbucket.org/mrabarnett/mrab-regex
  license: Python Software Foundation License
  summary: 'Alternative regular expression module, to replace re.'
