language: python
python:
  - "3.5"

sudo: false
addons:
  apt:
    packages:
    - texinfo
    - libftdi-dev
    - libusb-1.0-0-dev

install:
  - pip install pexpect
  - ./get-conda.sh
  - export PATH="$PATH:$HOME/conda/bin"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  - conda info -a

env:
  - PACKAGE=binutils-lm32-elf
  - PACKAGE=binutils-or1k-elf
  - PACKAGE=gcc-lm32-elf
  - PACKAGE=llvm-or1k-elf
  - PACKAGE=openocd
  - PACKAGE=sdcc

script:
  - python ./.travis-output.py output.log conda build $PACKAGE
  - conda install $PACKAGE --use-local

after_failure:
  - cat output.log

matrix:
  allow_failures:
    - env: PACKAGE=sdcc

