package:
    name: levenshtein
    version: "0.12.0"

source:
  fn: python-Levenshtein-0.12.0.tar.gz
  url: https://pypi.python.org/packages/source/p/python-Levenshtein/python-Levenshtein-0.12.0.tar.gz
  md5: e8cde197d6d304bbdc3adae66fec99fb

build:
  number: 0

requirements:
  build:
    - python
    - setuptools
  run:
    - python

about:
    home: http://github.com/ztane/python-Levenshtein
    license: GPL
    summary: 'Python extension for computing string edit distances and similarities'
