package:
    name: flterm
    version: 0

build:
  number: 1

source:
    git_url: https://github.com/m-labs/misoc
    git_tag: master

about:
    home: https://github.com/m-labs/misoc/blob/master/tools/flterm.c
    license: 3-clause BSD
    summary: 'Serial terminal to connect to the MiSoC UART.'
