package:
  name: quamash
  version: 0.5.4

source:
  fn: version-0.5.4.tar.gz
  url: https://github.com/harvimt/quamash/archive/version-0.5.4.tar.gz#md5=79a2cebf9c53a6fdd0e43f01f80e0451
  md5: 79a2cebf9c53a6fdd0e43f01f80e0451

build:
  number: 1
  noarch_python: true
  script: $PYTHON setup.py install

requirements:
  build:
    - python
    - setuptools
    - pyqt5
  run:
    - python
    - pyqt5

test:
  imports:
    - quamash

about:
  home: https://github.com/harvimt/quamash
  license: BSD
  summary: 'Implementation of the PEP 3156 Event-Loop with Qt'
