package:
  name: dateutil
  version: 2.4.2

source:
  fn: python-dateutil-2.4.2.tar.gz
  url: https://pypi.python.org/packages/source/p/python-dateutil/python-dateutil-2.4.2.tar.gz
  md5: 4ef68e1c485b09e9f034e10473e5add2

build:
  number: 0

requirements:
  build:
    - python
    - setuptools
    - six >=1.5
  run:
    - python
    - six >=1.5

test:
  imports:
    - dateutil
    - dateutil.zoneinfo

about:
  home: https://dateutil.readthedocs.org
  license: BSD
  summary: 'Extensions to the standard Python datetime module'
