package:
  name: pyqtgraph
  version: 0.9.10.1036edf

build:
  number: 0

source:
  git_url: https://github.com/pyqtgraph/pyqtgraph.git
  git_rev: 1036edf

requirements:
  build:
    - python
    - setuptools
    - numpy

  run:
    - python
    - numpy
    - pyqt >=4.7

test:
  imports:
    - pyqtgraph

about:
  home: http://www.pyqtgraph.org
  license: MIT License
  summary: 'Scientific Graphics and GUI Library for Python'
