package:
    name: pydaqmx
    version: "1.3.1"

source:
    git_url: https://github.com/clade/pydaqmx
    git_tag: master

build:
    number: 1

requirements:
    build:
        - python
        - setuptools
    run:
        - python

about:
    home: http://pythonhosted.org/PyDAQmx/
    license: BSD
    summary: PyDAQmx allows users to use data acquisition hardware from National Instruments with Python. It provides an interface between the NIDAQmx driver and Python. The package works on Windows and Linux.'
